sudo: required
services:
  - docker

before_install:
  - docker build -t cpavlatos/reactwebapp -f Dockerfile.dev . 

script:
  - docker run -e CI=true cpavlatos/reactwebapp npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "reactwebapp"
  env: "Reactwebapp-env"
  bucket_name: "elasticbeanstalk-us-west-1-579267201426"
  bucket_path: "reactwebapp"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

